run:
  timeout: 5m
  build-tags:
    - codeanalysis
  tests: true

issues:
  exclude-dirs:
    - api

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - unused
    - ineffassign
