services:

  chat-srv:
    container_name: chat_service
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
      - "${PORT}:${PORT}"
    env_file:
      - path: .env
        required: false
