definitions:
  v1.CreateChatRequest:
    properties:
      name:
        type: string
    type: object
  v1.CreateChatResponse:
    properties:
      id:
        type: string
    type: object
  v1.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  v1.CreateUserResponse:
    properties:
      id:
        type: string
    type: object
  v1.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  v1.LoginUserResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/chats:
    post:
      consumes:
      - application/json
      description: Creates new chat, runs in background and returns chat ID
      parameters:
      - description: Chat name
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/v1.CreateChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CreateChatResponse'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create chat
      tags:
      - Chats
  /api/v1/chats/{id}/connect:
    get:
      description: Upgrades http connection to websocket
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "422":
          description: Unprocessable Entity
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Upgrade http connection
      tags:
      - Chats
  /api/v1/users:
    post:
      description: Creates nes User, return his ID
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.CreateUserResponse'
        "422":
          description: Unprocessable Entity
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create New User
      tags:
      - Users
  /api/v1/users/login:
    post:
      description: Creates nes User, return his ID
      parameters:
      - description: User login data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.LoginUserResponse'
        "422":
          description: Unprocessable Entity
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create New User
      tags:
      - Users
swagger: "2.0"
